worker.h File Reference
Interface for worker process.
Functions
void worker (void)
Entry point for each GASPI worker process.
Detailed Description
Interface for worker process.
Author
Wiktor Szewczyk
Definition in file worker.h.
Function Documentation
worker()
void worker (void)
Entry point for each GASPI worker process.
Each worker:
Receives the dictionary from the manager
Processes assigned documents
Sends back feature vectors to the manager
Definition at line 21 of file worker.c.
References classify_text(), clear_hash_table(), GASPI_CHECK, MAX_DOC_SIZE, MAX_KEYWORDS, read_file_content(), receive_dictionary(), RESULT_OFFSET, RESULT_SEGMENT_ID, SHUTDOWN_NOTIF, WORK_AVAILABLE_NOTIF, WORK_DONE_NOTIF, WORK_NOTIF_ID, WORK_OFFSET, and WORK_SEGMENT_ID.
Referenced by main().