manager.h File Reference
Interface for the manager process.
Functions
void manager (const char *input_dir, const char *dict_file, const char *output_file, int size)
Entry point for the manager process.
Detailed Description
Interface for the manager process.
Author
Wiktor Szewczyk
Definition in file manager.h.
Function Documentation
manager()
void manager (const char * input_dir, const char * dict_file, const char * output_file, int size)
Entry point for the manager process.
The manager is responsible for:
Reading and broadcasting the dictionary
Scanning the input directory for text files
Distributing work to worker processes
Collecting and writing classification results
Parameters
input_dir Path to directory containing .txt files
dict_file Path to the dictionary file
output_file Path where results will be written
size Number of MPI processes
Definition at line 17 of file manager.c.
References broadcast_dictionary(), clear_hash_table(), DONE_MSG, FILE_MSG, list_txt_files(), MAX_FILES, MAX_KEYWORDS, open_output_file(), read_dictionary(), REQUEST_MSG, and VEC_MSG.
Referenced by main().