worker.c File Reference
Logic for a worker process participating in distributed document classification.
#include <GASPI.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "classifier.h"
#include "file_utils.h"
#include "gaspi_utils.h"
#include "hash_table.h"
#include "msg_consts.h"
#include "worker.h"
Functions
void worker (void)
Entry point for each GASPI worker process.
Detailed Description
Logic for a worker process participating in distributed document classification.
Author
Wiktor Szewczyk
Definition in file worker.c.
Function Documentation
worker()
void worker (void)
Entry point for each GASPI worker process.
Each worker:
Receives the dictionary from the manager
Processes assigned documents
Sends back feature vectors to the manager
Definition at line 21 of file worker.c.
References classify_text(), clear_hash_table(), GASPI_CHECK, MAX_DOC_SIZE, MAX_KEYWORDS, read_file_content(), receive_dictionary(), RESULT_OFFSET, RESULT_SEGMENT_ID, SHUTDOWN_NOTIF, WORK_AVAILABLE_NOTIF, WORK_DONE_NOTIF, WORK_NOTIF_ID, WORK_OFFSET, and WORK_SEGMENT_ID.
Referenced by main().