hash_table.c File Reference
Implementation of fixed-size chained hash table for keyword lookup.
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include "hash_table.h"
Functions
void clear_hash_table (void)
Frees all allocated hash table entries.
int find_word (const char *word)
Finds a word in the hash table.
int hash_func (const char *s)
Hash function for a word.
void insert_word (const char *word, int index)
Inserts a keyword into the hash table.
void to_lower (char *str)
Converts a string to lowercase in-place.
Variables
Node * hash_table [101]
Global hash table structure.
Detailed Description
Implementation of fixed-size chained hash table for keyword lookup.
Author
Wiktor Szewczyk
Definition in file hash_table.c.
Function Documentation
clear_hash_table()
void clear_hash_table (void)
Frees all allocated hash table entries.
Definition at line 49 of file hash_table.c.
References HASH_SIZE, and hash_table.
Referenced by manager(), and worker().
find_word()
int find_word (const char * word)
Finds a word in the hash table.
Parameters
word Word to find
Returns
Index in dictionary, or -1 if not found
Definition at line 36 of file hash_table.c.
References hash_func(), and hash_table.
Referenced by classify_text().
hash_func()
int hash_func (const char * s)
Hash function for a word.
Parameters
s Word to hash
Returns
Index in hash table
Definition at line 16 of file hash_table.c.
References HASH_SIZE.
Referenced by find_word(), and insert_word().
insert_word()
void insert_word (const char * word, int index)
Inserts a keyword into the hash table.
Parameters
word Keyword string
index Index in the dictionary
Definition at line 26 of file hash_table.c.
References hash_func(), and hash_table.
Referenced by read_dictionary(), and receive_dictionary().
to_lower()
void to_lower (char * str)
Converts a string to lowercase in-place.
Parameters
str String to lowercase
Definition at line 65 of file hash_table.c.
Referenced by classify_text(), and read_dictionary().
Variable Documentation
hash_table
Node* hash_table[101]
Global hash table structure.
Definition at line 14 of file hash_table.c.
Referenced by clear_hash_table(), find_word(), and insert_word().