manager.c File Reference
Orchestrates the classification by managing worker coordination and output collection.
#include <GASPI.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "file_utils.h"
#include "gaspi_utils.h"
#include "hash_table.h"
#include "manager.h"
#include "msg_consts.h"
Functions
void manager (const char *input_dir, const char *dict_file, const char *output_file, int processes_num)
Entry point for the manager process.
Detailed Description
Orchestrates the classification by managing worker coordination and output collection.
Author
Wiktor Szewczyk
Definition in file manager.c.
Function Documentation
manager()
void manager (const char * input_dir, const char * dict_file, const char * output_file, int processes_num)
Entry point for the manager process.
The manager is responsible for:
Reading and broadcasting the dictionary
Scanning the input directory for text files
Distributing work to worker processes
Collecting and writing classification results
Parameters
input_dir Path to directory containing .txt files
dict_file Path to the dictionary file
output_file Path where results will be written
processes_num Number of GASPI processes
Definition at line 20 of file manager.c.
References broadcast_dictionary(), clear_hash_table(), DICT_SEGMENT_ID, GASPI_CHECK, list_txt_files(), MAX_FILES, MAX_KEYWORDS, MAX_WORD_LEN, open_output_file(), read_dictionary(), RESULT_OFFSET, RESULT_SEGMENT_ID, SHUTDOWN_NOTIF, WORK_AVAILABLE_NOTIF, WORK_DONE_NOTIF, WORK_NOTIF_ID, WORK_OFFSET, WORK_SEGMENT_ID, and WORKER_DATA_SIZE.
Referenced by main().