file_utils.c File Reference
File reading, dictionary parsing, and dictionary broadcasting over MPI.
#include <mpi.h>
#include <dirent.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "file_utils.h"
#include "hash_table.h"
#include "msg_consts.h"
Functions
void broadcast_dictionary (char *keywords[], int num_keywords)
Broadcasts dictionary from manager to workers.
int list_txt_files (const char *dir_path, char files[][PATH_MAX], int max_files)
Lists all .txt files in a directory.
FILE * open_output_file (const char *output_path)
Opens the result output file for writing.
int read_dictionary (const char *dict_path, char *keywords[], int max_keywords)
Reads dictionary and builds global keyword list and hash table.
int read_file_content (const char *filename, char *buffer, size_t bufsize)
Reads entire content of a file into buffer.
void receive_dictionary (char *keywords[], int *num_keywords)
Receives dictionary in a worker and builds local keyword array and hash table.
Detailed Description
File reading, dictionary parsing, and dictionary broadcasting over MPI.
Author
Wiktor Szewczyk
Definition in file file_utils.c.
Function Documentation
broadcast_dictionary()
void broadcast_dictionary (char * keywords[], int num_keywords)
Broadcasts dictionary from manager to workers.
Parameters
keywords Array of keyword strings
num_keywords Number of keywords
Definition at line 83 of file file_utils.c.
References MAX_WORD_LEN.
Referenced by manager().
list_txt_files()
int list_txt_files (const char * dir_path, char files[][PATH_MAX], int max_files)
Lists all .txt files in a directory.
Parameters
dir_path Path to the directory
files Output array of full file paths
max_files Maximum number of files to find
Returns
Number of files found, or -1 on error
Definition at line 18 of file file_utils.c.
Referenced by manager().
open_output_file()
FILE * open_output_file (const char * output_path)
Opens the result output file for writing.
Parameters
output_path Output file path
Returns
FILE* handle or NULL on failure
Definition at line 52 of file file_utils.c.
Referenced by manager().
read_dictionary()
int read_dictionary (const char * dict_path, char * keywords[], int max_keywords)
Reads dictionary and builds global keyword list and hash table.
Parameters
dict_path Path to dictionary file
keywords Output array of allocated keyword strings
max_keywords Maximum allowed keyword count
Returns
Number of keywords read, or -1 on error
Definition at line 57 of file file_utils.c.
References insert_word(), MAX_WORD_LEN, and to_lower().
Referenced by manager().
read_file_content()
int read_file_content (const char * filename, char * buffer, size_t bufsize)
Reads entire content of a file into buffer.
Parameters
filename File to read
buffer Destination buffer
bufsize Maximum size of buffer
Returns
0 on success, -1 on error
Definition at line 40 of file file_utils.c.
Referenced by worker().
receive_dictionary()
void receive_dictionary (char * keywords[], int * num_keywords)
Receives dictionary in a worker and builds local keyword array and hash table.
Parameters
keywords Output array of keyword strings
num_keywords Output number of keywords
Definition at line 92 of file file_utils.c.
References insert_word(), and MAX_WORD_LEN.
Referenced by worker().