hash_table.h File Reference
Simple fixed-size chained hash table for word lookup.
Data Structures
struct node
Macros
#define HASH_SIZE 101
Size of the hash table (number of buckets).
Typedefs
typedef struct node Node
Functions
void clear_hash_table (void)
Frees all allocated hash table entries.
int find_word (const char *word)
Finds a word in the hash table.
int hash_func (const char *s)
Hash function for a word.
void insert_word (const char *word, int index)
Inserts a keyword into the hash table.
void to_lower (char *str)
Converts a string to lowercase in-place.
Variables
Node * hash_table [101]
Global hash table structure.
Detailed Description
Simple fixed-size chained hash table for word lookup.
Author
Wiktor Szewczyk
Definition in file hash_table.h.
Macro Definition Documentation
HASH_SIZE
#define HASH_SIZE 101
Size of the hash table (number of buckets).
The hash table uses fixed-size separate chaining with linked lists. A prime number is chosen to reduce the likelihood of collisions and distribute keys uniformly.
Definition at line 17 of file hash_table.h.
Typedef Documentation
Node
typedef struct node Node
Function Documentation
clear_hash_table()
void clear_hash_table (void)
Frees all allocated hash table entries.
Definition at line 49 of file hash_table.c.
References HASH_SIZE, and hash_table.
Referenced by manager(), and worker().
find_word()
int find_word (const char * word)
Finds a word in the hash table.
Parameters
word Word to find
Returns
Index in dictionary, or -1 if not found
Definition at line 36 of file hash_table.c.
References hash_func(), and hash_table.
Referenced by classify_text().
hash_func()
int hash_func (const char * s)
Hash function for a word.
Parameters
s Word to hash
Returns
Index in hash table
Definition at line 16 of file hash_table.c.
References HASH_SIZE.
Referenced by find_word(), and insert_word().
insert_word()
void insert_word (const char * word, int index)
Inserts a keyword into the hash table.
Parameters
word Keyword string
index Index in the dictionary
Definition at line 26 of file hash_table.c.
References hash_func(), and hash_table.
Referenced by read_dictionary(), and receive_dictionary().
to_lower()
void to_lower (char * str)
Converts a string to lowercase in-place.
Parameters
str String to lowercase
Definition at line 65 of file hash_table.c.
Referenced by classify_text(), and read_dictionary().
Variable Documentation
hash_table
Node* hash_table[101] [extern]
Global hash table structure.
Definition at line 14 of file hash_table.c.
Referenced by clear_hash_table(), find_word(), and insert_word().