classifier.h File Reference
Tokenization and text classification logic.
Macros
#define CLASSIFY_TOKENS " \n\t.,;:!?()[]{}\"'-"
Token delimiters for splitting text into words.
Functions
void classify_text (const char *text, int result[], int keyword_count)
Generates a classification vector from input text.
Detailed Description
Tokenization and text classification logic.
Author
Wiktor Szewczyk
Definition in file classifier.h.
Macro Definition Documentation
CLASSIFY_TOKENS
#define CLASSIFY_TOKENS " \n\t.,;:!?()[]{}\"'-"
Token delimiters for splitting text into words.
Definition at line 11 of file classifier.h.
Function Documentation
classify_text()
void classify_text (const char * text, int result[], int keyword_count)
Generates a classification vector from input text.
The function tokenizes the input string and compares each token to a global hash table containing dictionary keywords.
Parameters
text Input document text
result Output vector (must be zeroed and sized to keyword_count)
keyword_count Number of keywords in dictionary
Definition at line 13 of file classifier.c.
References CLASSIFY_TOKENS, find_word(), MAX_DOC_SIZE, and to_lower().
Referenced by worker().